"""add authorized scopes and asset inventory

Revision ID: 6ed8035c74fb
Revises: e7bd1dc77872
Create Date: 2026-08-23 22:00:26.389511
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6ed8035c74fb'
down_revision: Union[str, Sequence[str], None] = 'e7bd1dc77872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('vendor', sa.String(length=256), nullable=True),
    sa.Column('vendor_source', sa.String(length=128), nullable=True),
    sa.Column('vendor_database_version', sa.String(length=64), nullable=True),
    sa.Column('device_class_hint', sa.String(length=32), nullable=False),
    sa.Column('device_class_confidence', sa.String(length=16), nullable=False),
    sa.Column('os_family', sa.String(length=128), nullable=True),
    sa.Column('os_name', sa.String(length=512), nullable=True),
    sa.Column('os_generation', sa.String(length=64), nullable=True),
    sa.Column('os_accuracy', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint("state IN ('observed','responsive','unresponsive','unknown')", name='ck_assets_state'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'mac', name='uq_assets_audit_mac')
    )
    op.create_index('ix_assets_audit_device_class', 'assets', ['audit_id', 'device_class_hint'], unique=False)
    op.create_index('ix_assets_audit_state', 'assets', ['audit_id', 'state'], unique=False)
    op.create_index('ix_assets_audit_vendor', 'assets', ['audit_id', 'vendor'], unique=False)
    op.create_table('confirmed_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('address_families', sa.JSON(), nullable=False),
    sa.Column('address_count', sa.Integer(), nullable=False),
    sa.Column('route_context', sa.JSON(), nullable=False),
    sa.Column('timing_policy', sa.String(length=8), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'snapshot_hash', name='uq_confirmed_scopes_audit_hash')
    )
    op.create_index('ix_confirmed_scopes_audit_created', 'confirmed_scopes', ['audit_id', 'created_at'], unique=False)
    op.create_table('asset_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('family', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'address', name='uq_asset_addresses_audit_address')
    )
    op.create_index('ix_asset_addresses_asset', 'asset_addresses', ['asset_id'], unique=False)
    op.create_index('ix_asset_addresses_audit_family', 'asset_addresses', ['audit_id', 'family'], unique=False)
    op.create_table('asset_names',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'name', 'name_type', 'source', name='uq_asset_names_provenance')
    )
    op.create_index('ix_asset_names_audit_name', 'asset_names', ['audit_id', 'name'], unique=False)
    op.create_table('asset_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('observation_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evidence_reference', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_observations_asset_created', 'asset_observations', ['asset_id', 'created_at'], unique=False)
    op.create_index('ix_asset_observations_audit_created', 'asset_observations', ['audit_id', 'created_at'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('service_name', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=256), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('extra_info', sa.String(length=512), nullable=True),
    sa.Column('tunnel', sa.String(length=32), nullable=True),
    sa.Column('cpe', sa.JSON(), nullable=False),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'protocol', 'port', name='uq_services_asset_protocol_port')
    )
    op.create_index('ix_services_audit_name', 'services', ['audit_id', 'service_name'], unique=False)
    op.create_index('ix_services_audit_protocol_port', 'services', ['audit_id', 'protocol', 'port'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_audit_protocol_port', table_name='services')
    op.drop_index('ix_services_audit_name', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_asset_observations_audit_created', table_name='asset_observations')
    op.drop_index('ix_asset_observations_asset_created', table_name='asset_observations')
    op.drop_table('asset_observations')
    op.drop_index('ix_asset_names_audit_name', table_name='asset_names')
    op.drop_table('asset_names')
    op.drop_index('ix_asset_addresses_audit_family', table_name='asset_addresses')
    op.drop_index('ix_asset_addresses_asset', table_name='asset_addresses')
    op.drop_table('asset_addresses')
    op.drop_index('ix_confirmed_scopes_audit_created', table_name='confirmed_scopes')
    op.drop_table('confirmed_scopes')
    op.drop_index('ix_assets_audit_vendor', table_name='assets')
    op.drop_index('ix_assets_audit_state', table_name='assets')
    op.drop_index('ix_assets_audit_device_class', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
