"""create durable audit job schema

Revision ID: e7bd1dc77872
Revises: 
Create Date: 2026-08-23 19:08:08.050430
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e7bd1dc77872'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('environment_snapshot_reference', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('created','running','completed','failed','cancelled','interrupted')", name='ck_audits_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audits_status_created', 'audits', ['status', 'created_at'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_job_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("status IN ('starting','idle','running','stopped')", name='ck_workers_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_heartbeat', 'workers', ['heartbeat_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result_reference', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_component', sa.String(length=128), nullable=True),
    sa.Column('error_retryable', sa.Boolean(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('resource_key', sa.String(length=256), nullable=True),
    sa.Column('resource_group', sa.String(length=64), nullable=True),
    sa.Column('resource_limit', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled','interrupted')", name='ck_jobs_status'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_jobs_progress'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_audit_created', 'jobs', ['audit_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_queue_claim', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('schema_name', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.CheckConstraint("retention_class IN ('temporary','audit','debug','report')", name='ck_artifacts_retention_class'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path', name='uq_artifacts_relative_path')
    )
    op.create_index('ix_artifacts_audit_created', 'artifacts', ['audit_id', 'created_at'], unique=False)
    op.create_index('ix_artifacts_job_created', 'artifacts', ['job_id', 'created_at'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_audit_created', 'job_events', ['audit_id', 'created_at'], unique=False)
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_table('resource_locks',
    sa.Column('resource_key', sa.String(length=256), nullable=False),
    sa.Column('resource_group', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_key'),
    sa.UniqueConstraint('job_id', name='uq_resource_locks_job_id')
    )
    op.create_index('ix_resource_locks_group', 'resource_locks', ['resource_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_locks_group', table_name='resource_locks')
    op.drop_table('resource_locks')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_index('ix_job_events_audit_created', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_artifacts_job_created', table_name='artifacts')
    op.drop_index('ix_artifacts_audit_created', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_jobs_queue_claim', table_name='jobs')
    op.drop_index('ix_jobs_audit_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_workers_heartbeat', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_audits_status_created', table_name='audits')
    op.drop_table('audits')
    # ### end Alembic commands ###
